#!/bin/sh
self=`basename $0`
outdir=images
outfilename=$SHOTNAME			# get from environment vars

mkdir -p "$outdir"

case "$ACTION" in
    init)
	#echo "$self: INIT"
	# exit 1 # non-null exit to make gphoto2 call fail
	;;
    start)
	#echo "$self: START"
	;;
    download)
	#echo "$self: DOWNLOAD"
	ext="${ARGUMENT##*.}"

	echo mv "$ARGUMENT" to "$outfilename.$ext"
	mv "$ARGUMENT" "$outdir/$outfilename.$ext"

	#chmod 777 $outdir_tmp/$outfilename
	;;
    stop)
	#echo "$self: STOP"
	;;
    *)
	echo "$self: Unknown action: $ACTION"
	;;
esac

exit 0
